version: '3.9'

services:
  mysql:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    volumes:
      - /tmp/time-planner-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time-planner
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password