server:
  port: ${PORT:8080}
spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:mysql://aws.connect.psdb.cloud/time-planner?sslMode=VERIFY_IDENTITY
    username: pxf233u543uothebwx2z
    password: pscale_pw_W8tUxGPNyb1HC4Qcf97zP0Ul8BUzUSZeZqvIhw5AEVo
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

