server:
  address: 0.0.0.0
spring:
  application.name: time-planner-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/time-planner-dc611
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    operationsSorter: method
  show-actuator: true
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
