server:
  address: 0.0.0.0
  port: 8080
spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost/time_planner
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
client:
  scheduler:
    base-url: http://localhost:8082/v1
    connection-timeout: 15
