server:
  address: 0.0.0.0
  port: ${PORT:8080}
spring:
  liquibase:
    enabled: true
  datasource:
    hikari:
      maximum-pool-size: 25
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
client:
  scheduler:
    base-url: http://localhost:8082/v1
    connection-timeout: 15
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

